# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: []
    tags: ["*"]


jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.dir.outputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - id: dir
        run: echo "::set-output name=dir::$(ls -d packages/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')"

  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - run: yarn
    - run: cd packages/sign
    - run: yarn
    - run: yarn run build
    - run: cd ../..

  testing:
    runs-on: ubuntu-latest
    needs: [directories, build]
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)!='sign'}}
    steps:
    - run: echo ${{ matrix.dir }}
    - run: cd ${{ matrix.dir }}
    - run: yarn
    - run: yarn run build
    - run: yarn run test
